
FROM node:12.14.0

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-pay-service

WORKDIR /data/freelog-pay-service

COPY . /data/freelog-pay-service

RUN npm install --production

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 5056
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 5056

CMD [ "npm", "start" ]
