FROM node:10.5.0

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-pay-service

WORKDIR /data/freelog-pay-service

COPY . /data/freelog-pay-service

RUN npm install

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 5055
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 5055

CMD [ "npm", "start" ]
