FROM daocloud.io/node:8.5

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-pay-service

WORKDIR /data/freelog-pay-service

COPY . /data/freelog-pay-service

RUN npm install

#ENV
#VOLUME ['/opt/logs','/data/logs']

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 5055

EXPOSE 7055

CMD [ "npm", "start" ]
