FROM node:14.6.0-alpine

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-pay-service

WORKDIR /data/freelog-pay-service

COPY . /data/freelog-pay-service

RUN npm install --production

#ENV
#VOLUME ['/opt/logs','/data/logs']

ENV NODE_ENV prod
ENV EGG_SERVER_ENV prod
ENV PORT 7055

EXPOSE 7055

CMD [ "npm", "start" ]
